In [24]:
import numpy as np
import pandas as pd

In [9]:
print np.zeros(3)
print np.ones(3)


[ 0.  0.  0.]
[ 1.  1.  1.]


In [12]:
print np.zeros((4,4))

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [27]:
data = [1,2,3]
data2 = ['a','b','c']
data3 = ['a','b','c']
test = zip(data,data2)
print test

[(1, 'a'), (2, 'b'), (3, 'c')]


In [34]:
df = pd.DataFrame(zip(data,data2))
df.columns = ["A","B"]
print df

   A  B
0  1  a
1  2  b
2  3  c


In [35]:
df.isnull()

A      B
0  False  False
1  False  False
2  False  False

In [39]:
df.head(2)

A  B
0  1  a
1  2  b

In [41]:
df.columns

Index([u'A', u'B'], dtype='object')